INSERT INTO teams (team_name)
VALUES ('Mercedes-AMG Petronas Formula One Team'),
       ('Red Bull Racing'),
       ('Scuderia Ferrari'),
       ('Alpine F1 Team'),
       ('McLaren F1 Team'),
       ('Scuderia AlphaTauri'),
       ('Aston Martin Cognizant Formula One Team'),
       ('Alfa Romeo Racing Orlen'),
       ('Haas F1 Team'),
       ('Williams Racing'),
       ('Racing Point F1 Team)'),
       ('Lotus F1 Team'),
       ('Sauber F1 Team'),
       ('Brawn GP'),
       ('BMW Sauber F1 Team'),
       ('Team Lotus'),
       ('Marussia F1 Team'),
       ('Force India F1 Team'),
       ('Tyrrell Racing Team');
